"""ML Service Constants"""

# Face Detection
DEFAULT_MIN_FACE_AREA_RATIO = 0.04
DEFAULT_NUM_JITTERS = 3
DEFAULT_MODEL = "hog"  # hog or cnn

# Face Encoding
ENCODING_MIN_FACE_AREA_RATIO = 0.05
ENCODING_NUM_JITTERS = 5

# Face Matching
DEFAULT_MATCH_THRESHOLD = 0.6
CONFIDENT_THRESHOLD = 0.50
UNCERTAIN_THRESHOLD = 0.60

# Error Codes
ERROR_NO_FACE = "NO_FACE_FOUND"
ERROR_MULTIPLE_FACES = "MULTIPLE_FACES_FOUND"
ERROR_FACE_TOO_SMALL = "FACE_TOO_SMALL"
ERROR_INVALID_IMAGE = "INVALID_IMAGE"
ERROR_PROCESSING = "PROCESSING_ERROR"
