"""ML Service Constants"""

# Face Detection
DEFAULT_MIN_FACE_AREA_RATIO = 0.04
DEFAULT_NUM_JITTERS = 3
DEFAULT_MODEL = "hog"  # hog or cnn

# Face Encoding
ENCODING_MIN_FACE_AREA_RATIO = 0.05
ENCODING_NUM_JITTERS = 5

# Face Matching
DEFAULT_MATCH_THRESHOLD = 0.6
CONFIDENT_THRESHOLD = 0.50
UNCERTAIN_THRESHOLD = 0.60

# Image Validation
MAX_IMAGE_SIZE_BYTES = 5_242_880  # 5MB
MAX_BASE64_SIZE = int(MAX_IMAGE_SIZE_BYTES * 1.37)  # Base64 is ~37% larger
MAX_IMAGE_DIMENSION = 4096  # Max width or height
ALLOWED_IMAGE_FORMATS = {"JPEG", "PNG", "JPG"}

# Error Codes
ERROR_NO_FACE = "NO_FACE_FOUND"
ERROR_MULTIPLE_FACES = "MULTIPLE_FACES_FOUND"
ERROR_FACE_TOO_SMALL = "FACE_TOO_SMALL"
ERROR_INVALID_IMAGE = "INVALID_IMAGE"
ERROR_IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"
ERROR_INVALID_FORMAT = "INVALID_FORMAT"
ERROR_INVALID_DIMENSIONS = "INVALID_DIMENSIONS"
ERROR_PROCESSING = "PROCESSING_ERROR"
